version: '3'

services:
  db:
    env_file: docker/.env
    image: postgres:alpine
    ports:
      - 5432:5432
    # volumes:
    #   - dbdata:/var/lib/postgresql/data

  riptide:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ./start.sh
    depends_on:
      - db
    env_file: docker/.env
    stdin_open: true
    tty: true



volumes:
  dbdata:
