[tool.poetry]
name = "riptide"
version = "0.1.0"
description = ""
authors = ["Ranieri Althoff <ranisalt@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
cagrex = "^0.4.3"
psycopg2 = "^2.7"

[tool.poetry.dev-dependencies]
